steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - >-
        gcr.io/${PROJECT_ID}/${REPO_NAME}:${BRANCH_NAME}_${SHORT_SHA}_${BUILD_ID}
      - '-f'
      - Dockerfile
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        gcr.io/${PROJECT_ID}/${REPO_NAME}:${BRANCH_NAME}_${SHORT_SHA}_${BUILD_ID}
  - name: gcr.io/cloud-builders/gcloud
    args:
      - source
      - repos
      - clone
      - github_mirror-media_kubernetes-configs
      - ./dockerignore/kubernetes-configs
  - name: launcher.gcr.io/google/ubuntu1604
    args:
      - '-c'
      - >
        # install kustomize

        curl -s
        "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"
        | bash


        # mv kubernetes-configs folder

        mv ./dockerignore/kubernetes-configs /workspace/kubernetes-configs

        # read kustimization roots from substitution variable

        IFS=',' read -r -a kustomize_roots <<< $_KUSTOMIZATION_ROOTS


        for kr in "${kustomize_roots[@]}"

        do

        # generate kubernetes configs from each kustimization root

        /workspace/kustomize build "$kr" >> $_FILE_TO_DEPLOY

        # append separate line after each generated kubernetes config

        echo "---" >> $_FILE_TO_DEPLOY

        done


        # print out configs

        cat $_FILE_TO_DEPLOY
    entrypoint: bash
  - name: gcr.io/cloud-builders/kubectl
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_KUBERNETES_COMPUTE_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_KUBERNETES_CLUSTER}'
    args:
      - apply
      - '-f'
      - $_FILE_TO_DEPLOY
      - '--validate=true'
timeout: 900s
substitutions:
  _KUSTOMIZATION_ROOTS: .
  _FILE_TO_DEPLOY: config-to-deploy.txt
  _KUBERNETES_COMPUTE_REGION: asia-east1
  _KUBERNETES_CLUSTER: tv-cluster
images:
  - 'gcr.io/${PROJECT_ID}/${REPO_NAME}:${BRANCH_NAME}_${SHORT_SHA}_${BUILD_ID}'

