steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - >-
        gcr.io/${PROJECT_ID}/${REPO_NAME}:${BRANCH_NAME}_${SHORT_SHA}_${BUILD_ID}
      - '-f'
      - Dockerfile
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        gcr.io/${PROJECT_ID}/${REPO_NAME}:${BRANCH_NAME}_${SHORT_SHA}_${BUILD_ID}
images:
  - 'gcr.io/${PROJECT_ID}/${REPO_NAME}:${BRANCH_NAME}_${SHORT_SHA}_${BUILD_ID}'

