---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ksa-feed
  namespace: cron
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: feed-google-news-rss
  namespace: cron
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: ksa-feed
          containers:
            - name: mirror-tv-feed-google-news-rss
              image: gcr.io/mirror-tv-275709/mirror-tv-feed:20210202-1
              workingDir: /cronjobs/feed
              command: ["./start.sh"]
              args:
                - $(EXECFOLDER)
                - $(EXECSCRIPT)
              env:
                - name: EXECFOLDER
                  value: ./mirror-tv/google_news_rss
                - name: EXECSCRIPT
                  value: generate_google_news_rss.py
          restartPolicy: OnFailure
