{
    "base_url": 'https://www.mnews.tw',
    "configs_endpoint": ['/',
                         '/story/aboutus',
                         '/schedule',
                         '/topic',
                         '/anchorperson',
                         '/story/privacy',
                         '/story/webauthorization',
                         '/story/press-self-regulation', ],
    "template": {
        "sitmap": {
            "header": '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">', 
            "urltag": '\n<url><loc>{}</loc><lastmod>{}</lastmod><changefreq>"hourly"</changefreq><priority>{}</priority></url>',
            "endtag": ' \n</urlset>'},
        "sitemap_index": {
            "header": '<?xml version="1.0" encoding="UTF-8"?><sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">', 
            "urltag": '<sitemap><loc>{}</loc><lastmod>{}</lastmod></sitemap>', 
            "endtag": '</sitemapindex>'}
    },
    "file":{
        "bucket_name" :'static-mnews-tw-dev',
        "destination_prefix" : 'rss/',
    }

}